<a href="https://colab.research.google.com/github/SerniQ/python_1/blob/master/jjj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving Housing.csv to Housing (1).csv


In [5]:
df = pd.read_csv("Housing.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [6]:
df.head()

price  area  bedrooms  ...  parking  prefarea furnishingstatus
0  13300000  7420         4  ...        2       yes        furnished
1  12250000  8960         4  ...        3        no        furnished
2  12250000  9960         3  ...        2       yes   semi-furnished
3  12215000  7500         4  ...        3       yes        furnished
4  11410000  7420         4  ...        2        no        furnished

[5 rows x 13 columns]

In [7]:
df.head(3)

price  area  bedrooms  ...  parking  prefarea furnishingstatus
0  13300000  7420         4  ...        2       yes        furnished
1  12250000  8960         4  ...        3        no        furnished
2  12250000  9960         3  ...        2       yes   semi-furnished

[3 rows x 13 columns]

In [8]:
df.tail(8)

price  area  bedrooms  ...  parking  prefarea furnishingstatus
537  1890000  1700         3  ...        0        no      unfurnished
538  1890000  3649         2  ...        0        no      unfurnished
539  1855000  2990         2  ...        1        no      unfurnished
540  1820000  3000         2  ...        2        no      unfurnished
541  1767150  2400         3  ...        0        no   semi-furnished
542  1750000  3620         2  ...        0        no      unfurnished
543  1750000  2910         3  ...        0        no        furnished
544  1750000  3850         3  ...        0        no      unfurnished

[8 rows x 13 columns]

In [9]:
df["area"]

0      7420
1      8960
2      9960
3      7500
4      7420
       ... 
540    3000
541    2400
542    3620
543    2910
544    3850
Name: area, Length: 545, dtype: int64

In [10]:
df[["area", "stories", "parking"]]

area  stories  parking
0    7420        3        2
1    8960        4        3
2    9960        2        2
3    7500        2        3
4    7420        2        2
..    ...      ...      ...
540  3000        1        2
541  2400        1        0
542  3620        1        0
543  2910        1        0
544  3850        2        0

[545 rows x 3 columns]

In [11]:
df[df["area"]>5000]

price  area  bedrooms  ...  parking  prefarea furnishingstatus
0    13300000  7420         4  ...        2       yes        furnished
1    12250000  8960         4  ...        3        no        furnished
2    12250000  9960         3  ...        2       yes   semi-furnished
3    12215000  7500         4  ...        3       yes        furnished
4    11410000  7420         4  ...        2        no        furnished
..        ...   ...       ...  ...      ...       ...              ...
487   2870000  5400         4  ...        0        no      unfurnished
488   2852500  5200         4  ...        0        no      unfurnished
494   2730000  6800         2  ...        0        no      unfurnished
520   2450000  7700         2  ...        0        no      unfurnished
531   2233000  5300         3  ...        0       yes      unfurnished

[236 rows x 13 columns]

In [18]:
df[
   (df["area"]>5000) &\
   (df["bathrooms"]==3) &\
   (df["basement"]=="yes")
]

price  area  bedrooms  ...  parking  prefarea furnishingstatus
5   10850000  7500         3  ...        2       yes   semi-furnished
11   9681000  6000         4  ...        2        no   semi-furnished
33   8190000  5960         3  ...        1        no      unfurnished

[3 rows x 13 columns]

In [19]:
df.describe()

price          area  ...     stories     parking
count  5.450000e+02    545.000000  ...  545.000000  545.000000
mean   4.766729e+06   5150.541284  ...    1.805505    0.693578
std    1.870440e+06   2170.141023  ...    0.867492    0.861586
min    1.750000e+06   1650.000000  ...    1.000000    0.000000
25%    3.430000e+06   3600.000000  ...    1.000000    0.000000
50%    4.340000e+06   4600.000000  ...    2.000000    0.000000
75%    5.740000e+06   6360.000000  ...    2.000000    1.000000
max    1.330000e+07  16200.000000  ...    4.000000    3.000000

[8 rows x 6 columns]

In [20]:
df.sum()

price                                                      2597867440
area                                                          2807045
bedrooms                                                         1616
bathrooms                                                         701
stories                                                           984
mainroad            yesyesyesyesyesyesyesyesyesyesyesyesyesyesyesy...
guestroom           nonononoyesnononoyesyesnoyesnonononoyesnoyesno...
basement            nonoyesyesyesyesnonoyesnoyesyesnononoyesyesnon...
hotwaterheating     nononononononononononoyesnoyesnonononononoyesn...
airconditioning     yesyesnoyesyesyesyesnoyesyesyesnoyesnononoyesy...
parking                                                           378
prefarea            yesnoyesyesnoyesyesnoyesyesyesnoyesnoyesnoyesn...
furnishingstatus    furnishedfurnishedsemi-furnishedfurnishedfurni...
dtype: object

In [22]:
df["area"].mean()

5150.54128440367

In [23]:
df.count()

price               545
area                545
bedrooms            545
bathrooms           545
stories             545
mainroad            545
guestroom           545
basement            545
hotwaterheating     545
airconditioning     545
parking             545
prefarea            545
furnishingstatus    545
dtype: int64

In [24]:
df.corr()

price      area  bedrooms  bathrooms   stories   parking
price      1.000000  0.535997  0.366494   0.517545  0.420712  0.384394
area       0.535997  1.000000  0.151858   0.193820  0.083996  0.352980
bedrooms   0.366494  0.151858  1.000000   0.373930  0.408564  0.139270
bathrooms  0.517545  0.193820  0.373930   1.000000  0.326165  0.177496
stories    0.420712  0.083996  0.408564   0.326165  1.000000  0.045547
parking    0.384394  0.352980  0.139270   0.177496  0.045547  1.000000

In [26]:
df.isna().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [27]:
import numpy as np

In [28]:
tmp_arr = np.array([1,2,3,4,5])
type(tmp_arr)

numpy.ndarray

In [30]:
tmp_arr.dtype

dtype('int64')

In [33]:
#@title
np.array([1,2,3,"siema"])

array(['1', '2', '3', 'siema'], dtype='<U21')

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
np.ones(10)*10

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [48]:
tmp_array = np.array([[1,2,3],[4,5,6]])
tmp_arr

array([1, 2, 3, 4, 5])

In [47]:
print(tmp_arr)

[1 2 3 4 5]


In [49]:
tmp_arr.dtype

dtype('int64')

In [50]:
tmp_arr.shape

(5,)